Makefile.am
configure.ac

In some situations, building the Python bindings may not be desirable
or even possible, for example in the context of cross-compiled
embedded systems, Python may not even be available on the target
platform.
In order to address this, this commit adds a
--with-python/--without-python option to the configure script, which
allows to specify whether Python bindings should be built or not. Of
course, in order to preserve the current behavior, the Python bindings
are built by default (if neither --with-python nor --without-python is
passed).
This change would for example be useful for embedded Linux build
systems such as Buildroot (http://buildroot.org).
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>

Make the Python bindings build conditional

---

src/SerialPort.h
src/SerialStreamBuf.h

On certain architectures (namely Sparc), the maximum baud rate exposed
by the kernel headers is B2000000. Therefore, the current libserial
code doesn't build for the Sparc and Sparc64 architectures due to
this.
In order to address this problem, this patch tests the value of
__MAX_BAUD. If it's higher than B2000000 then we assume we're on an
architecture that supports all baud rates up to B4000000. Otherwise,
we simply don't support the baud rates above B2000000.
Fixes build failures such as:
./SerialPort.h:88:24: error: 'B2500000' was not declared in this scope
BAUD_2500000 = B2500000,
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>

Don't use high baudrates when not available

---

src/SerialStreamBuf.cc

If compiled with clang 3.4 on x86-64, SetBaudRate would crash with SIGILL
because of the ud2 instruction inserted because of the missing return
statement
* SetBaudRate was not actually returning anything, which doesn't work
with some compiler/platform combinations
Also fixed the following warnings:
* Error checking on SetParity, SetBaudRate and SetFlowControl was not
using the right enumeration values during default

Fixed undefined behavior/illegal instruction crash

---

CMakeLists.txt
src/SerialPort.cpp
src/SerialPort.h
src/SerialPortConstants.h
src/SerialStream.cc
src/SerialStreamBuf.cc
src/SerialStreamBuf.h
test/LibSerialTest.cpp

Hi CrayzeeWulf,
I've added a unit test for threaded serial stream communications to mirror the serial port threaded communications test and renamed a mutex lock variable to match the buffer it is locking in this pull request.
It appears that both the serial port and serial stream communications suffer from a similar issue when used in a threaded application, so I am continuing to investigate and learn what I can.
-Mark

Serial Stream Multi-Thread unit test added

---

src/PosixSignalDispatcher.cpp
src/SerialPort.cpp

This PR simply adds std:: scope resolution to all strerror() method calls.  The goal of this PR is to remedy _Build issues_ #89 .
-Mark

Added std:: scope resolution operator to strerror() calls.

---

src/PosixSignalDispatcher.cpp
src/SerialPort.cpp

This PR adds `#include <stdlib.h>` to SerialPort.cpp and  `#include <cerrno>` to SerialPort.cpp and PosixSignalDispatcher.cpp to fix the compiler errors reported in Build Issues #89.
-Mark

Added #include <cerrno> and #include <stdlib.h> to fix Build Issues #89

---

doxygen.conf.in
src/SerialPort.cpp
src/SerialPort.h
src/SerialPortConstants.h
src/SerialStream.h
src/SerialStreamBuf.cpp
src/SerialStreamBuf.h

Updates to documentation, added explicit std:: scope resolution operators to memset() calls, and added #includes to address compiler errors on virtual machines.
-Mark

Fixes for Build Issues #89

---

README.md
compile.sh
examples/main_page_example.cpp
examples/serial_port_read.cpp
examples/serial_port_read_write.cpp
examples/serial_port_write.cpp
examples/serial_stream_read_write.cpp
examples/serial_stream_write.cpp
sip/SerialPort.sip
src/SerialPort.cpp
src/SerialPort.h
src/SerialPortConstants.h
src/SerialStream.cpp
src/SerialStream.h
src/SerialStreamBuf.cpp
src/SerialStreamBuf.h
test/UnitTests.cpp

Hi CrayzeeWUlf,
This PR updates the SerialPort Class Read() methods to allow indefinite amount of data to be read before the timeout has elapsed. Unit tests and documentation has also been updated to describe and test those cases.
Please let me know if you have any questions!
-Mark

Updated SerialPort Read() methods

---

CMakeLists.txt
README.md

This PR adds a few compiler flags that might help in the future and removes a few flags that are already invoked by -Wall and -Wextra.  Additional packages are also added to the list that were required to build with a new installation of Ubuntu 17.10.

Update CMakeLists.txt and README required package list.

---

test/UnitTests.cpp

Hi CrayzeeWulf,
This PR updates the unit tests to better capture default hardware flow control line states from verifiable set states.
-Mark

Update the unit tests to verify default hardware flow control line states.

---

Makefile.am
configure.ac

test uses gtest so allow the user to disable tests to avoid adding a
unneeded dependency
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

Make tests conditional

---

src/SerialPort.h
test/UnitTests.cpp
test/UnitTests.h

Hi CrayzeeWulf,
I cut appropriate sections of code out of the UnitTests.cpp file into a header file in this merge request.
Appropriate testing using both the make build and cmake build has been conducted with all previous functionality preserved.  Doxy documentation has allso been completed for the header file.
-Mark

Break apart UnitTests.cpp to utilize a header file

---

COPYING
COPYING.LESSER

Hi CrayzeeWulf,
This PR modifies the contents of COPPYING.LESSER file to the LGPL2.0 content rather than the LGPL3.0 content of previous.  This PR also standardizes tabs to spaces, rather than the previous mix of both in the COPYING file.
This PR specifically addresses issue #107.  At present, I plan on accomplishing additional work to migrate the license from LGPL2.0 will be raised in a subsequent issue and PR.
-Mark

Update COPYING.LESSER content to reflect LGPL2.0

---

sip/configure.py.in

Hello!
This PR adds c++11 compiler flags to the sip/configure.py.in script to fix a compiler error encountered by Jeff Franks.
Let me know if you have any questions on this PR!
-Mark

Added c++11 compiler flag per Jeffrey Franks patch instructions.

---

src/SerialPort.cpp

size_t can be defined as an unsigned int instead of long unsigned int so
replace 1UL to (size_t)1 when calling max function
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

SerialPort.cpp: fix build when size_t is an unsigned int

---

src/SerialPort.cpp

On certain architectures (namely Sparc), the maximum baud rate exposed
by the kernel headers is B2000000. Therefore, the current libserial
code doesn't build for the Sparc and Sparc64 architectures due to
this.
In order to address this problem, this patch tests the value of
__MAX_BAUD. If it's higher than B2000000 then we assume we're on an
architecture that supports all baud rates up to B4000000. Otherwise,
we simply don't support the baud rates above B2000000.
Fixes build failures such as:
SerialPort.cpp: In member function 'int LibSerial::SerialPort::Implementation::GetBitRate(const LibSerial::BaudRate&) const':
SerialPort.cpp:1226:14: error: 'BAUD_2000000' is not a member of 'LibSerial::BaudRate'
case BaudRate::BAUD_2000000:
Fixes:
- …

SerialPort.cpp: don't use high baudrates when not available

---

src/SerialPort.cpp
src/libserial/SerialPortConstants.h

Hi Crayzee Wulf,
This PR just adds in a check to SerialPort.cpp for linux specific baud rates in following the discussion from PR #127 .  It also modifies the comment style to single line rather than block as is done in other instances in libserial.
This PR passes hardware testing on an Ubuntu 18.10 machine with FTDI USB to serial port hardware adapters.
-Mark

Added check for linux specific baud rates to SerialPort.cpp.

---

examples/serial_port_read.cpp
examples/serial_port_read_write.cpp
examples/serial_port_write.cpp
examples/serial_stream_read.cpp
examples/serial_stream_read_write.cpp
examples/serial_stream_write.cpp

Hi Crayzee Wulf,
This PR adds try/catch blocks around the Open() calls in the example code. (Making the assumption that is probably the most likely place for an early example failure to occur.)
I've also added `#define`'s for the port names so that readers will hopefully have an easier time spotting them and modifying them.
Let me know if you'd like to see anything done differently here and I will gladly carry it out!
-Mark 
EDIT: Hardware tests have been verified passing on all example tests

Added try/catch blocks to the serial port and serial stream Open() calls and #defines for port names.

---

README.md
examples/main_page_example.cpp
examples/serial_port_read.cpp
examples/serial_port_read_write.cpp
examples/serial_port_write.cpp
examples/serial_stream_read.cpp
examples/serial_stream_read_write.cpp
examples/serial_stream_write.cpp
test/MultiThreadUnitTests.cpp
test/SerialPortUnitTests.cpp
test/SerialStreamUnitTests.cpp
test/UnitTests.cpp
test/UnitTests.h

Hi Crayzee Wulf,
This PR:
- Adds a few lines to the README.md to help future users with potential issues,
- Standardizes the declaration of 
```
constexpr const char* const SERIAL_PORT_1 = "/dev/ttyUSB0" ;
constexpr const char* const SERIAL_PORT_2 = "/dev/ttyUSB1" ;
```
in the `examples/` directory, and
- Renames `TEST_SERIAL_PORT_X` to `SERIAL_PORT_X` so that usage is uniform between unit tests and example code.
The PR is quite a few LOC, but the diff is pretty straightforward.
All unit tests and example executables pass hardware testing.
Let me know if you have any questions on this PR!
-Mark

Update the README and standardize SERIAL_PORT_1 and SERIAL_PORT_2 declarations

---

src/SerialPort.cpp
src/SerialStream.cpp
src/SerialStreamBuf.cpp

This PR fixes issue #135. Major updates are:
- Destructors of all classes were updated to make sure that they [never throw any exceptions](https://isocpp.org/wiki/faq/exceptions#dtors-shouldnt-throw).
- `SerialPort::Close()` method was updated so that failure to restore the old state of the serial port does not throw an exception. Only failure to actually close the serial port is considered significant enough to throw an exception. 
All unit tests are passing.

Fix issue #135

---

README.md
dockerfiles/centos/7/Dockerfile
dockerfiles/debian/buster/Dockerfile
dockerfiles/ubuntu/18.04/Dockerfile

Added docker files for testing libserial builds on various Linux distributions. The following Linux distributions are included:
* CentOS 7
* Debian Buster
* Ubuntu 18.04
Support for additional distributions will be added in the future.

Dockerfiles

---

CMakeLists.txt
dockerfiles/debian/buster/Dockerfile
dockerfiles/ubuntu/16.04/Dockerfile
dockerfiles/ubuntu/18.04/Dockerfile

Fixes to build on Ubuntu 16.04 to address issue #137
- Dropped minimum required CMake version to 3.5.
- Added checks to make sure that we are using C++ compiler with C++14
support enabled.

Fixes issue #137

---

src/SerialPort.cpp

Hi @crayzeewulf , 
This PR changes the exception types thrown in a few methods in the SerialPort class that I **think** were copy paste errors that I likely made previously.
If these exception types are correct please let me know and we can close this PR to leave them as-is.
EDIT: Hardware unit tests all pass with this PR.
Thanks!
-Mark

Modify exception types to better match the intent in a few SerialPort class methods.

---

test/SerialPortUnitTests.cpp
test/SerialStreamUnitTests.cpp

Hi @crayzeewulf ,
This PR quiets a compiler warning in the unit test framework. Hardware unit tests are passing with this PR and the warning is silenced.
-Mark

Augment SerialPortUnitTest and SerialStreamUnitTest tests to quiet compiler warnings.

---

src/SerialPort.cpp
src/SerialStreamBuf.cpp
src/libserial/SerialPort.h
src/libserial/SerialStreamBuf.h
test/SerialPortUnitTests.cpp
test/SerialPortUnitTests.h
test/SerialStreamUnitTests.cpp
test/SerialStreamUnitTests.h

Hi Crayzee Wulf,
This PR attempts to address compilation on for other POSIX users for at least one known problem area. If there is a better way to handle this that you have identified just let me know! 
@79rpm , I *think this PR will take care of issue #143.  Would you be willing to try this out and let us know if it allows you to build the library?  If it works we can accept this PR and close out the issue.
Thanks!
-Mark
**UPDATED:** Hardware unit tests passing.

Apply linux specific #ifdef __linux__ encapsulation of the GetAvailableSerialPort() methods.

---

README.md

Hi @crayzeewulf , this PR adds python3-sphinx-rtd-theme to the README.md file to help close out #139.
Let me know if you think this is not needed, (we can just close this out if that's the case)!
-Mark

Add python3-sphinx-rtd-theme to the README.md file.

---

src/SerialPort.cpp
src/SerialStreamBuf.cpp
src/libserial/SerialPort.h
src/libserial/SerialStream.h
src/libserial/SerialStreamBuf.h

Hi @crayzeewulf , in reviewing code tonight I noticed that a handful of methods were lacking const specifiers where they could be added.  I don't recall if this was intentional or simply an oversight.
This PR adds const specifiers to method arguments that can allow the addition.  Please go ahead and close this PR if they were omitted previously by design!
Thanks!
-Mark
EDIT: All unit tests are passing with this PR.  Please let me know if you'd like to see anything done differently!

Add const specifiers to method arguments that were missing.

---

CMakeLists.txt

Added the required steps in the CMake build to populate the pkg-config template and install it into the pkg-config directory.

Add pkg-config install to cmake build.

---

src/SerialPort.cpp
src/libserial/SerialPortConstants.h

We should use `errno` and `std::streerror()` when `errno` is expected to
be set by a recent call. In other case we need to use a custom error
message. This should fix #161.

Fix for #161.

---

src/SerialPort.cpp

Hi @crayzeewulf !,
Pretty straightforward PR.  Let me know if you have any questions!
Thanks!
-Mark

Use static_cast<>() in std::max() calls.

---

src/SerialPort.cpp
src/SerialStream.cpp
src/SerialStreamBuf.cpp

Hi @crayzeewulf , 
As tracked in #184, @thewoz reports that this fixes his issue in macosX.
I'd prefer to find an alternative `ifdef` encapsulation limited to the `serial_struct` usage in the `SerialPort::GetAvailableSerialPorts()` function to allow macos compatibility within that function, but for now, hopefully this is at least a quick review and easy.
Let me know your thoughts!
-Mark

Add additional linux specific encapsulation.

---

src/SerialPort.cpp

As explained in the description of call_with_retry template, system calls that are interrupted and return EINTR shall be repeated. The original code occasionally throws an exception when writing data to the serial port.
This fixes https://github.com/crayzeewulf/libserial/issues/194

Handle EINTR when calling tcdrain

---

src/SerialPort.cpp
src/SerialStream.cpp
src/SerialStreamBuf.cpp
src/libserial/SerialPort.h
src/libserial/SerialStream.h
src/libserial/SerialStreamBuf.h

After ending program execution and closing the opened serial port, the serial port could not be opened again because it is busy. After some investigation, this could be tracked down to the exclusive access to the serial port which is being set in `Open(...)`.
To fix this, the serial port must be released from exclusive access in `Close()`:
```cpp
// Release the serial port from exclusive access.
if (mExclusiveAccess)
{
// NOLINTNEXTLINE (cppcoreguidelines-pro-type-vararg)
if(call_with_retry(ioctl, this->mFileDescriptor, TIOCNXCL) == -1)
{
err_msg += ", ";
err_msg += std::strerror(errno);
}
}
```
As an additional configuration option, I've added the `exclusive` flag that allows to specify whether to require exclusive access to the serial port or not.

Release exclusive access to serial port on close

---

CMakeLists.txt

Update to the latest gtest tag v1.16
Hardware tested on Ubuntu 24.04LTS.

Update gtest tag to v1.16
